name: 'Unit Test setup'
description: 'Checkout code and setup JDK 17'
inputs: {}
outputs: {}
runs:
  using: 'composite'
  steps:
    # Checkout
    - uses: actions/checkout@v3

    # Setup JDK
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17

    # Allow gradle execution
    - name: Make Gradle executable
      run: chmod +x ./gradlew